[project]
name = "serpscoop"
version = "0.1.0"
description = "My first MCP application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fastapi-mcp>=0.2.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
